# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
# Twilio SMS secrets

twilioAccountSID: AC8f230f64baecd2bb60e02625b79142b4
twilioAuthToken: 78bf2a081f6705d13ff800876a935946
twilioNumber: "+17207091596"
clientNumber: ""

# Twitter secrets
twitterConsumerKey: "kA7gKxSbjKQ7JXRSHQCnfAMUN"
twitterConsumerSecret: "1t3R52Qp8DfAt1MbXfra9xA51OQrumBfpUBFhAoCckUlQ53pQs"
twitterAccessToken: "850774011713925120-lSMiCOx77TSbjpqtfXBPD2KVaRmo24T"
twitterAccessTokenSecret: "XtoF6sJPK8e1WLlCnL0RiTyAShO2NKv4g4ks3ZEp11YXX"
